id = "textile"
name = "Textile"
version = "0.1.0"
schema_version = 1
authors = ["withersky"]
description = "Textile markup language support for Zed"
repository = "https://github.com/withersky/zed-textile"

[grammars.textile]
repository = "https://github.com/withersky/zed-textile.git"
rev = "bcec55bbca9e82a701022b361d01d97fc38388b2"
